#!/usr/bin/env bash
# bioAF Installer
# Checks prerequisites, generates environment config, and prepares the system
# for running bioAF via the ./bioaf management script.
#
# Usage:
#   ./install.sh              Interactive install (prompts for values)
#   ./install.sh --help       Show usage
#   ./install.sh check-prereqs   Check prerequisites only
#   ./install.sh generate-env    Generate docker/.env from .env.example

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"
ENV_FILE="$SCRIPT_DIR/docker/.env"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
red()    { printf '\033[0;31m%s\033[0m\n' "$*"; }
green()  { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
bold()   { printf '\033[1m%s\033[0m\n' "$*"; }

usage() {
    bold "bioAF Installer"
    echo ""
    echo "Usage: ./install.sh [command] [options]"
    echo ""
    bold "Commands:"
    echo "  (none)            Run full interactive install"
    echo "  check-prereqs     Check that required tools are installed"
    echo "  generate-env      Generate docker/.env from .env.example"
    echo "  --help, -h        Show this usage information"
    echo ""
    bold "Options:"
    echo "  --non-interactive   Skip prompts, use generated defaults"
    echo "  --force             Overwrite existing docker/.env"
    echo ""
}

# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------
check_prereqs() {
    local missing=0

    bold "Checking prerequisites..."
    echo ""

    # Docker
    if command -v docker &>/dev/null; then
        green "  docker ......... $(docker --version 2>/dev/null | head -1)"
    else
        red "  docker ......... NOT FOUND"
        missing=1
    fi

    # Docker Compose (v2 plugin)
    if docker compose version &>/dev/null 2>&1; then
        green "  docker compose . $(docker compose version 2>/dev/null | head -1)"
    else
        red "  docker compose . NOT FOUND"
        missing=1
    fi

    # Git
    if command -v git &>/dev/null; then
        green "  git ............ $(git --version 2>/dev/null)"
    else
        red "  git ............ NOT FOUND"
        missing=1
    fi

    # openssl (for secret generation)
    if command -v openssl &>/dev/null; then
        green "  openssl ........ $(openssl version 2>/dev/null | head -1)"
    else
        red "  openssl ........ NOT FOUND"
        missing=1
    fi

    echo ""

    if [ "$missing" -ne 0 ]; then
        red "Some prerequisites are missing. Please install them before continuing."
        return 1
    fi

    green "All prerequisites satisfied."
    return 0
}

# ---------------------------------------------------------------------------
# .env generation
# ---------------------------------------------------------------------------
generate_env() {
    local non_interactive=false
    local force=false

    for arg in "$@"; do
        case "$arg" in
            --non-interactive) non_interactive=true ;;
            --force)           force=true ;;
        esac
    done

    # Check for .env.example
    if [ ! -f "$ENV_EXAMPLE" ]; then
        red "ERROR: .env.example not found at $ENV_EXAMPLE"
        return 1
    fi

    # Check for existing .env
    if [ -f "$ENV_FILE" ] && [ "$force" = false ]; then
        yellow "docker/.env already exists. Use --force to overwrite."
        return 0
    fi

    mkdir -p "$(dirname "$ENV_FILE")"

    # Generate secrets
    local pg_password
    local secret_key
    pg_password=$(openssl rand -hex 16)
    secret_key=$(openssl rand -hex 32)

    if [ "$non_interactive" = true ]; then
        # Auto-generate everything
        cat > "$ENV_FILE" <<ENVEOF
# Generated by bioAF installer on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# PostgreSQL
POSTGRES_USER=bioaf
POSTGRES_PASSWORD=$pg_password
POSTGRES_DB=bioaf

# Backend
DATABASE_URL=postgresql+asyncpg://bioaf:${pg_password}@db:5432/bioaf
SECRET_KEY=$secret_key

# Frontend
NEXT_PUBLIC_API_URL=

# Environment
BIOAF_ENVIRONMENT=production
ENVEOF
    else
        # Interactive: prompt for optional overrides
        echo ""
        bold "Generating environment configuration..."
        echo ""
        echo "Press Enter to accept defaults."
        echo ""

        read -rp "PostgreSQL user [bioaf]: " pg_user
        pg_user=${pg_user:-bioaf}

        read -rp "PostgreSQL database [bioaf]: " pg_db
        pg_db=${pg_db:-bioaf}

        read -rp "Public URL (leave blank for localhost): " public_url
        public_url=${public_url:-}

        cat > "$ENV_FILE" <<ENVEOF
# Generated by bioAF installer on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# PostgreSQL
POSTGRES_USER=$pg_user
POSTGRES_PASSWORD=$pg_password
POSTGRES_DB=$pg_db

# Backend
DATABASE_URL=postgresql+asyncpg://${pg_user}:${pg_password}@db:5432/${pg_db}
SECRET_KEY=$secret_key

# Frontend
NEXT_PUBLIC_API_URL=$public_url

# Environment
BIOAF_ENVIRONMENT=production
ENVEOF
    fi

    green "Environment file written to docker/.env"
    return 0
}

# ---------------------------------------------------------------------------
# Full install
# ---------------------------------------------------------------------------
full_install() {
    local non_interactive=false
    local force=false

    for arg in "$@"; do
        case "$arg" in
            --non-interactive) non_interactive=true ;;
            --force)           force=true ;;
        esac
    done

    bold "=== bioAF Installer ==="
    echo ""

    # Step 1: Prerequisites
    check_prereqs || exit 1
    echo ""

    # Step 2: Generate .env
    local env_args=()
    [ "$non_interactive" = true ] && env_args+=(--non-interactive)
    [ "$force" = true ] && env_args+=(--force)
    generate_env "${env_args[@]}" || exit 1
    echo ""

    # Step 3: Show next steps
    bold "=== Installation Complete ==="
    echo ""
    echo "Next steps:"
    echo "  1. Review docker/.env and adjust if needed"
    echo "  2. Run './bioaf setup' to build, migrate, and create your admin account"
    echo ""
    echo "Or run individual commands:"
    echo "  ./bioaf build      Build container images"
    echo "  ./bioaf start      Start all services"
    echo "  ./bioaf migrate    Run database migrations"
    echo "  ./bioaf status     Check service status"
    echo "  ./bioaf help       Show all commands"
    echo ""
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
command="${1:-}"

case "$command" in
    check-prereqs)
        shift
        check_prereqs
        ;;
    generate-env)
        shift
        generate_env "$@"
        ;;
    --help|-h)
        usage
        ;;
    "")
        shift 2>/dev/null || true
        full_install "$@"
        ;;
    *)
        # Pass-through flags for full install (e.g., --non-interactive)
        full_install "$@"
        ;;
esac
