# bioAF SLURM Configuration
# Generated by Terraform templatefile()

ClusterName=bioaf
SlurmctldHost=${controller_hostname}

# Authentication
AuthType=auth/munge
CryptoType=crypto/munge

# Accounting
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=localhost
AccountingStoragePort=6819
JobAcctGatherType=jobacct_gather/cgroup
JobAcctGatherFrequency=30

# Scheduling
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory

# Logging
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid

# Process tracking
ProctrackType=proctrack/cgroup
TaskPlugin=task/cgroup

# Cloud scaling
SuspendProgram=/usr/local/bin/slurm-suspend.sh
ResumeProgram=/usr/local/bin/slurm-resume.sh
SuspendTime=${idle_timeout}
ResumeTimeout=300
TreeWidth=65535

# Partitions
PartitionName=standard Nodes=bioaf-slurm-standard-[0-${standard_max_nodes_minus1}] MaxTime=7-00:00:00 Default=YES State=UP
PartitionName=interactive Nodes=bioaf-slurm-interactive-[0-${interactive_max_nodes_minus1}] MaxTime=1-00:00:00 State=UP

# Node definitions (cloud nodes)
NodeName=bioaf-slurm-standard-[0-${standard_max_nodes_minus1}] State=CLOUD CPUs=${standard_cpus} RealMemory=${standard_memory_mb}
NodeName=bioaf-slurm-interactive-[0-${interactive_max_nodes_minus1}] State=CLOUD CPUs=${interactive_cpus} RealMemory=${interactive_memory_mb}
