"""Renders a JSON provenance report as Markdown."""

from __future__ import annotations

from typing import Any


def _v(val: Any) -> str:
    """Format a value for display, rendering None as '--'."""
    if val is None:
        return "--"
    if isinstance(val, dict):
        return str(val)
    return str(val)


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    """Build a pipe-delimited Markdown table."""
    lines = []
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        lines.append("| " + " | ".join(_v(c) for c in row) + " |")
    return "\n".join(lines)


def _user_str(user: dict[str, Any] | None) -> str:
    if not user:
        return "--"
    return user.get("email") or user.get("name") or str(user.get("id", "--"))


def _size_str(size_bytes: int | None) -> str:
    if size_bytes is None:
        return "--"
    if size_bytes < 1024:
        return f"{size_bytes} B"
    if size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    if size_bytes < 1024 * 1024 * 1024:
        return f"{size_bytes / (1024 * 1024):.1f} MB"
    return f"{size_bytes / (1024 * 1024 * 1024):.1f} GB"


class MarkdownRenderer:
    @staticmethod
    def render(entity_type: str, json_report: dict[str, Any]) -> str:
        renderer = _MD_RENDERERS.get(entity_type)
        if not renderer:
            raise ValueError(f"Unknown entity type: {entity_type}")
        return renderer(json_report)


def _render_project_md(report: dict[str, Any]) -> str:
    entity = report["entity"]
    parts: list[str] = []
    parts.append(f"# Provenance Report: {entity.get('name', 'Unknown Project')}")
    parts.append("")
    parts.append(f"**Report generated:** {report['generated_at']}")
    parts.append(f"**Generated by:** {report['generated_by']}")
    parts.append(f"**bioAF version:** {report.get('bioaf_version', '--')}")
    parts.append(f"**Schema version:** {report['schema_version']}")
    parts.append("")
    parts.append("---")
    parts.append("")

    # Metadata
    parts.append("## Metadata")
    parts.append("")
    parts.append(
        _table(
            ["Field", "Value"],
            [
                ["ID", entity.get("id")],
                ["Name", entity.get("name")],
                ["Status", entity.get("status")],
                ["Owner", _user_str(entity.get("owner"))],
                ["Description", entity.get("description")],
                ["Created", entity.get("created_at")],
            ],
        )
    )
    parts.append("")

    # Experiments
    experiments = entity.get("experiments", [])
    parts.append(f"## Experiments ({len(experiments)})")
    parts.append("")
    if experiments:
        parts.append(
            _table(
                ["ID", "Name", "Status", "Samples"],
                [[e.get("id"), e.get("name"), e.get("status"), e.get("sample_count")] for e in experiments],
            )
        )
    else:
        parts.append("No experiments.")
    parts.append("")

    # Audit trail
    _append_audit_trail(parts, report.get("audit_trail", []))

    return "\n".join(parts)


def _render_experiment_md(report: dict[str, Any]) -> str:
    entity = report["entity"]
    parts: list[str] = []
    parts.append(f"# Provenance Report: {entity.get('name', 'Unknown Experiment')}")
    parts.append("")
    parts.append(f"**Report generated:** {report['generated_at']}")
    parts.append(f"**Generated by:** {report['generated_by']}")
    parts.append(f"**bioAF version:** {report.get('bioaf_version', '--')}")
    parts.append(f"**Schema version:** {report['schema_version']}")
    parts.append("")
    parts.append("---")
    parts.append("")

    # Experiment Metadata
    parts.append("## Experiment Metadata")
    parts.append("")
    parts.append(
        _table(
            ["Field", "Value"],
            [
                ["ID", entity.get("id")],
                ["Name", entity.get("name")],
                ["Project ID", entity.get("project_id")],
                ["Status", entity.get("status")],
                ["Owner", _user_str(entity.get("owner"))],
                ["Design Type", entity.get("design_type")],
                ["Protocol Version", entity.get("protocol_version")],
                ["Start Date", entity.get("start_date")],
                ["Created", entity.get("created_at")],
            ],
        )
    )
    parts.append("")

    # Samples
    samples = entity.get("samples", [])
    parts.append(f"## Samples ({len(samples)})")
    parts.append("")
    if samples:
        parts.append(
            _table(
                ["Sample ID", "External ID", "Organism", "Tissue Type", "QC Status", "Library Prep"],
                [
                    [
                        s.get("id"),
                        s.get("external_id"),
                        s.get("biological", {}).get("organism"),
                        s.get("biological", {}).get("tissue_type"),
                        s.get("qc", {}).get("status"),
                        s.get("technical", {}).get("library_prep_method"),
                    ]
                    for s in samples
                ],
            )
        )
    else:
        parts.append("No samples.")
    parts.append("")

    # Pipeline Runs
    runs = entity.get("pipeline_runs", [])
    parts.append(f"## Pipeline Runs ({len(runs)})")
    parts.append("")
    for run in runs:
        parts.append(f"### Run: {run.get('pipeline_name')} v{_v(run.get('pipeline_version'))} (ID: {run.get('id')})")
        parts.append("")
        parts.append(f"**Status:** {run.get('status')}")
        parts.append(f"**Submitted by:** {_user_str(run.get('submitted_by'))}")
        parts.append(f"**Started:** {_v(run.get('started_at'))} | **Completed:** {_v(run.get('completed_at'))}")
        parts.append("")

        # Parameters
        params = run.get("parameters")
        if params:
            parts.append("#### Parameters")
            parts.append("")
            parts.append(
                _table(
                    ["Parameter", "Value"],
                    [[k, v] for k, v in params.items()],
                )
            )
            parts.append("")

        # Environment
        env = run.get("environment", {})
        if env:
            parts.append("#### Environment")
            parts.append("")
            parts.append(
                _table(
                    ["Property", "Value"],
                    [[k, v] for k, v in env.items() if v is not None],
                )
            )
            parts.append("")

        # Process Steps
        processes = run.get("processes", [])
        if processes:
            parts.append("#### Process Steps")
            parts.append("")
            parts.append(
                _table(
                    ["Step", "Status", "Duration", "CPU", "Memory", "Exit Code"],
                    [
                        [
                            p.get("name"),
                            p.get("status"),
                            f"{p.get('duration_seconds')}s" if p.get("duration_seconds") else "--",
                            p.get("cpu_usage"),
                            f"{p.get('memory_peak_gb')} GB" if p.get("memory_peak_gb") else "--",
                            p.get("exit_code"),
                        ]
                        for p in processes
                    ],
                )
            )
            parts.append("")

    # Files
    files = entity.get("files", {})
    raw = files.get("raw", [])
    results = files.get("results", [])
    parts.append("## Files")
    parts.append("")

    parts.append(f"### Raw Files ({len(raw)})")
    parts.append("")
    if raw:
        parts.append(
            _table(
                ["Filename", "Type", "Size", "MD5", "SHA-256"],
                [
                    [
                        f.get("filename"),
                        f.get("file_type"),
                        _size_str(f.get("size_bytes")),
                        f.get("md5"),
                        f.get("sha256"),
                    ]
                    for f in raw
                ],
            )
        )
    else:
        parts.append("No raw files.")
    parts.append("")

    parts.append(f"### Result Files ({len(results)})")
    parts.append("")
    if results:
        parts.append(
            _table(
                ["Filename", "Type", "Size", "MD5", "Source Run"],
                [
                    [
                        f.get("filename"),
                        f.get("file_type"),
                        _size_str(f.get("size_bytes")),
                        f.get("md5"),
                        f.get("source_pipeline_run_id"),
                    ]
                    for f in results
                ],
            )
        )
    else:
        parts.append("No result files.")
    parts.append("")

    # Audit trail
    _append_audit_trail(parts, report.get("audit_trail", []))

    return "\n".join(parts)


def _render_sample_md(report: dict[str, Any]) -> str:
    entity = report["entity"]
    parts: list[str] = []
    parts.append(f"# Provenance Report: Sample {entity.get('external_id') or entity.get('id')}")
    parts.append("")
    parts.append(f"**Report generated:** {report['generated_at']}")
    parts.append(f"**Generated by:** {report['generated_by']}")
    parts.append(f"**Schema version:** {report['schema_version']}")
    parts.append("")
    parts.append("---")
    parts.append("")

    parts.append("## Metadata")
    parts.append("")
    bio = entity.get("biological", {})
    tech = entity.get("technical", {})
    parts.append(
        _table(
            ["Field", "Value"],
            [
                ["ID", entity.get("id")],
                ["External ID", entity.get("external_id")],
                ["Organism", bio.get("organism")],
                ["Tissue Type", bio.get("tissue_type")],
                ["Library Prep", tech.get("library_prep_method")],
                ["QC Status", entity.get("qc", {}).get("status")],
                ["Status", entity.get("status")],
            ],
        )
    )
    parts.append("")

    # Files
    files = entity.get("files", [])
    parts.append(f"## Files ({len(files)})")
    parts.append("")
    if files:
        parts.append(
            _table(
                ["Filename", "Type", "Size", "MD5"],
                [[f.get("filename"), f.get("file_type"), _size_str(f.get("size_bytes")), f.get("md5")] for f in files],
            )
        )
    parts.append("")

    _append_audit_trail(parts, report.get("audit_trail", []))
    return "\n".join(parts)


def _render_pipeline_run_md(report: dict[str, Any]) -> str:
    entity = report["entity"]
    parts: list[str] = []
    parts.append(f"# Provenance Report: {entity.get('pipeline_name')} v{_v(entity.get('pipeline_version'))}")
    parts.append("")
    parts.append(f"**Report generated:** {report['generated_at']}")
    parts.append(f"**Generated by:** {report['generated_by']}")
    parts.append(f"**Schema version:** {report['schema_version']}")
    parts.append("")
    parts.append("---")
    parts.append("")

    parts.append("## Metadata")
    parts.append("")
    parts.append(
        _table(
            ["Field", "Value"],
            [
                ["ID", entity.get("id")],
                ["Pipeline", entity.get("pipeline_name")],
                ["Version", entity.get("pipeline_version")],
                ["Status", entity.get("status")],
                ["Submitted by", _user_str(entity.get("submitted_by"))],
                ["Reference Genome", entity.get("reference_genome")],
                ["Alignment", entity.get("alignment_algorithm")],
            ],
        )
    )
    parts.append("")

    processes = entity.get("processes", [])
    if processes:
        parts.append(f"## Process Steps ({len(processes)})")
        parts.append("")
        parts.append(
            _table(
                ["Step", "Status", "Duration", "CPU", "Memory", "Exit Code"],
                [
                    [
                        p.get("name"),
                        p.get("status"),
                        f"{p.get('duration_seconds')}s" if p.get("duration_seconds") else "--",
                        p.get("cpu_usage"),
                        f"{p.get('memory_peak_gb')} GB" if p.get("memory_peak_gb") else "--",
                        p.get("exit_code"),
                    ]
                    for p in processes
                ],
            )
        )
        parts.append("")

    _append_audit_trail(parts, report.get("audit_trail", []))
    return "\n".join(parts)


def _render_artifact_md(report: dict[str, Any]) -> str:
    entity = report["entity"]
    parts: list[str] = []
    parts.append(f"# Provenance Report: {entity.get('filename')}")
    parts.append("")
    parts.append(f"**Report generated:** {report['generated_at']}")
    parts.append(f"**Generated by:** {report['generated_by']}")
    parts.append(f"**Schema version:** {report['schema_version']}")
    parts.append("")
    parts.append("---")
    parts.append("")

    checksums = entity.get("checksums", {})
    parts.append("## Metadata")
    parts.append("")
    parts.append(
        _table(
            ["Field", "Value"],
            [
                ["ID", entity.get("id")],
                ["Filename", entity.get("filename")],
                ["Type", entity.get("file_type")],
                ["Artifact Type", entity.get("artifact_type")],
                ["Size", _size_str(entity.get("size_bytes"))],
                ["MD5", checksums.get("md5")],
                ["SHA-256", checksums.get("sha256")],
            ],
        )
    )
    parts.append("")

    # Source information
    source = entity.get("source", {})
    source_type = source.get("type", "unknown")
    parts.append("## Source")
    parts.append("")

    if source_type == "notebook_output" and source.get("notebook_session"):
        ns = source["notebook_session"]
        parts.append(
            _table(
                ["Field", "Value"],
                [
                    ["Source Type", "Notebook session output"],
                    ["Session ID", ns.get("id")],
                    ["Session Type", ns.get("session_type")],
                    ["Status", ns.get("status")],
                    ["Resources", f"{ns.get('cpu_cores')} CPU, {ns.get('memory_gb')} GB"],
                    ["Started", ns.get("started_at")],
                    ["Stopped", ns.get("stopped_at")],
                    ["Git Branch", ns.get("git_branch_name")],
                    ["Git Commit", ns.get("git_commit_hash")],
                ],
            )
        )
        parts.append("")

        env = ns.get("environment")
        if env:
            parts.append("### Environment")
            parts.append("")
            parts.append(
                _table(
                    ["Field", "Value"],
                    [
                        ["Environment", env.get("environment_name")],
                        ["Version", f"v{env.get('version_number')}.{env.get('build_number')}"],
                        ["Format", env.get("definition_format")],
                        ["Image URI", env.get("image_uri")],
                    ],
                )
            )
            parts.append("")

        input_files = ns.get("input_files", [])
        if input_files:
            parts.append("### Input Files")
            parts.append("")
            parts.append(
                _table(
                    ["ID", "Filename", "Type"],
                    [[f.get("id"), f.get("filename"), f.get("file_type")] for f in input_files],
                )
            )
            parts.append("")

    elif source_type == "pipeline_output" and source.get("pipeline_run"):
        pr = source["pipeline_run"]
        parts.append(
            _table(
                ["Field", "Value"],
                [
                    ["Source Type", "Pipeline output"],
                    ["Pipeline", pr.get("pipeline_name")],
                    ["Version", pr.get("pipeline_version")],
                    ["Run ID", pr.get("id")],
                    ["Status", pr.get("status")],
                    [
                        "Submitted By",
                        pr.get("submitted_by", {}).get("name")
                        if isinstance(pr.get("submitted_by"), dict)
                        else pr.get("submitted_by"),
                    ],
                ],
            )
        )
        parts.append("")
    else:
        parts.append(f"Source type: {source_type}")
        parts.append("")
        uploader = entity.get("uploader")
        if uploader:
            name = uploader.get("name") if isinstance(uploader, dict) else uploader
            parts.append(f"Uploaded by: {name}")
            parts.append("")

    # Related data
    related = report.get("related_data", {})
    linked_samples = related.get("linked_samples", [])
    if linked_samples:
        parts.append("## Linked Samples")
        parts.append("")
        parts.append(
            _table(
                ["ID", "External ID", "Organism"],
                [[s.get("id"), s.get("external_id"), s.get("organism")] for s in linked_samples],
            )
        )
        parts.append("")

    downstream = related.get("downstream_usage", [])
    if downstream:
        parts.append("## Downstream Usage")
        parts.append("")
        rows = []
        for d in downstream:
            if "pipeline_run_id" in d:
                rows.append([f"Pipeline run {d['pipeline_run_id']}", d.get("pipeline_name")])
            elif "notebook_session_id" in d:
                rows.append([f"Notebook session {d['notebook_session_id']}", d.get("session_type")])
        if rows:
            parts.append(_table(["Consumer", "Name/Type"], rows))
            parts.append("")

    _append_audit_trail(parts, report.get("audit_trail", []))
    return "\n".join(parts)


def _append_audit_trail(parts: list[str], audit_trail: list[dict[str, Any]]) -> None:
    parts.append("## Audit Trail")
    parts.append("")
    if audit_trail:
        parts.append(
            _table(
                ["Timestamp", "User", "Action", "Details"],
                [
                    [
                        a.get("timestamp"),
                        _user_str(a.get("user")),
                        a.get("action"),
                        str(a.get("details") or "--"),
                    ]
                    for a in audit_trail
                ],
            )
        )
    else:
        parts.append("No audit trail entries.")
    parts.append("")


_MD_RENDERERS: dict[str, Any] = {
    "project": _render_project_md,
    "experiment": _render_experiment_md,
    "sample": _render_sample_md,
    "pipeline_run": _render_pipeline_run_md,
    "artifact": _render_artifact_md,
}
