"""Tests for JWT secret key validation at startup."""

import pytest

from app.config import INSECURE_JWT_SECRETS, validate_jwt_secret


class TestValidateJwtSecret:
    """Reject known-bad and weak JWT secrets before the app accepts traffic."""

    def test_rejects_dev_default(self):
        with pytest.raises(SystemExit):
            validate_jwt_secret("dev-secret-key-change-in-production")

    def test_rejects_compose_default(self):
        with pytest.raises(SystemExit):
            validate_jwt_secret("CHANGE_ME_TO_RANDOM_STRING")

    def test_rejects_change_me(self):
        with pytest.raises(SystemExit):
            validate_jwt_secret("CHANGE_ME")

    def test_rejects_empty_string(self):
        with pytest.raises(SystemExit):
            validate_jwt_secret("")

    def test_rejects_short_secret(self):
        """HS256 needs at least 32 bytes of entropy."""
        with pytest.raises(SystemExit):
            validate_jwt_secret("tooshort")

    def test_accepts_valid_secret(self):
        """A 64-char hex string (32 bytes) generated by openssl rand -hex 32."""
        secret = "a" * 64
        validate_jwt_secret(secret)  # should not raise

    def test_blocklist_is_lowercase_normalized(self):
        """Ensure case variations of known-bad secrets are also caught."""
        for bad in INSECURE_JWT_SECRETS:
            with pytest.raises(SystemExit):
                validate_jwt_secret(bad.upper())

    def test_accepts_real_generated_secret(self):
        """Simulate what install.sh produces: openssl rand -hex 32."""
        import secrets

        real_secret = secrets.token_hex(32)
        validate_jwt_secret(real_secret)  # should not raise
