"""GEO export README generator — instructions and metadata for the export package."""

import logging
from datetime import datetime, timezone

from app.services.geo.validation import ValidationReport

logger = logging.getLogger("bioaf.geo.readme")


def generate_readme(
    experiment_name: str,
    validation_report: ValidationReport,
    files_data: dict | None,
    missing_checksum_files: list[str],
) -> str:
    """Generate README.txt for the GEO export package."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    summary = validation_report.summary

    lines = [
        "=" * 70,
        "GEO Submission Package — bioAF Export",
        "=" * 70,
        "",
        f"Experiment: {experiment_name}",
        f"Export date: {now}",
        f"Pipeline run ID: {validation_report.pipeline_run_id or 'N/A'}",
        "",
        "-" * 70,
        "VALIDATION SUMMARY",
        "-" * 70,
        f"Total fields checked: {summary.total_fields}",
        f"  Complete:               {summary.complete}",
        f"  Populated (unvalidated):{summary.populated_unvalidated}",
        f"  Missing (required):     {summary.missing_required}",
        f"  Missing (recommended):  {summary.missing_recommended}",
        "",
    ]

    if summary.missing_required > 0:
        lines.append("WARNING: Some required fields are missing. Look for")
        lines.append("'[REQUIRED - please fill in]' placeholders in the Excel file.")
        lines.append("")

    if missing_checksum_files:
        lines.append("WARNING: The following files are missing MD5 checksums:")
        for f in missing_checksum_files:
            lines.append(f"  - {f}")
        lines.append("")

    lines.extend([
        "-" * 70,
        "PACKAGE CONTENTS",
        "-" * 70,
        "  geo_metadata_*.xlsx     — Pre-filled GEO metadata template",
        "  md5_checksums.txt       — MD5 checksums for data files",
        "  validation_report.json  — Machine-readable validation report",
        "  validation_report.txt   — Human-readable validation summary",
        "  README.txt              — This file",
        "",
        "-" * 70,
        "DATA FILES (for FTP upload)",
        "-" * 70,
        "The following data files must be uploaded to GEO's FTP server.",
        "They are NOT included in this ZIP (too large).",
        "",
    ])

    if files_data:
        for f in files_data.get("raw_files", []):
            gcs = f.get("gcs_uri", "N/A")
            lines.append(f"  RAW: {f.get('filename', 'unknown')}")
            lines.append(f"       GCS: {gcs}")
        for f in files_data.get("processed_files", []):
            gcs = f.get("gcs_uri", "N/A")
            lines.append(f"  PROCESSED: {f.get('filename', 'unknown')}")
            lines.append(f"       GCS: {gcs}")
        lines.append("")

    lines.extend([
        "-" * 70,
        "SUBMISSION INSTRUCTIONS",
        "-" * 70,
        "1. Review and complete the Excel metadata file",
        "   - Fill in any '[REQUIRED - please fill in]' placeholders",
        "   - Verify values flagged as 'unvalidated' are correct",
        "",
        "2. Upload data files to GEO's FTP server:",
        "   Host: ftp-private.ncbi.nlm.nih.gov",
        "   Login: geo",
        "   Password: (obtain from GEO submission portal)",
        "   Directory: uploads/your_email_address/",
        "",
        "3. Submit via GEO's web interface:",
        "   https://www.ncbi.nlm.nih.gov/geo/info/submission.html",
        "   - Upload the metadata Excel file",
        "   - Specify the FTP directory containing your data files",
        "",
        "4. Wait for GEO curator review (typically 1-3 business days)",
        "",
        "=" * 70,
        "Generated by bioAF — https://github.com/not-that-guy-again/bioAF",
        "=" * 70,
        "",
    ])

    return "\n".join(lines)
